name: SpectatorPlus
version: "$version"
description: "$description"
website: "https://github.com/hpfxd/SpectatorPlus"
api-version: "1.20"
main: "com.hpfxd.spectatorplus.paper.SpectatorPlugin"
load: STARTUP
authors:
  - hpfxd

permissions:
  spectatorplus.sync.experience:
    description: "Allows the player to receive the experience value of the spectated target"
    default: true
  spectatorplus.sync.food:
    description: "Allows the player to receive the food value of the spectated target"
    default: true
  spectatorplus.sync.hotbar:
    description: "Allows the player to receive the hotbar items and selected slot of the spectated target"
    default: true
  spectatorplus.sync.inventory:
    description: "Allows the player to receive the full inventory of the spectated target when a screen is open"
    default: true
  spectatorplus.sync.screen:
    description: "Allows the player to receive the open screen of the spectated target (e.g. a chest)"
    default: true
